# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lroux <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/06 14:23:48 by lroux             #+#    #+#              #
#    Updated: 2019/01/22 17:01:17 by lroux            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

PROJECT	:= libnode
NAME	:= $(PROJECT).a

SRCDIR	:= srcs
OBJDIR	:= objs
INCDIR	:= incs

SRCS	:= core.c push.c pop.c sort.c

LIBS	:= libft
LIBDIR	:= ..

# Include core
include ../lib.mk

